# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    working_directory: ~/emerald
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd ./back-end && npm install && npm run test
      - add_ssh_keys:
          fingerprints:
            - "7f:7c:8b:00:18:6c:c8:3f:10:39:34:4a:5e:a3:cf:74"
      - run: cd ./back-end && cp ~/.ssh/id_rsa_7f7c8b00186cc83f1039344a5ea3cf74 ./ec2.pem && chmod 400 ./ec2.pem 
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run: sudo npm install -g pm2 
      - run: cd ./back-end && pm2 deploy ecosystem.config.js production --force

workflows:
  version: 2
  build_and_test:
    jobs: 
      - build:
          filters:
            branches:
              only: master



